# Generated by Django 2.2.3 on 2019-07-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('RH', 'Human Resources'), ('ADM', 'Administration'), ('DEV', 'Development'), ('IT', 'Information Technology')], max_length=100),
        ),
    ]
